#!/usr/bin/env bash
# Nginx must be run, and listen on port 80 of all the server’s ipv4 
#kill $(ps aux | pgrep 'nginx')
service nginx stop
rm /etc/nginx/sites-available/default
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
/etc/init.d/nginx restart
