#!/usr/bin/env bash
# Displays "Best school" x10 & "Hi" in the 9th iteration
# using- while loop

i=0

while [ $i -lt 10 ]
do
	if [ $i -eq 9 ]
	then
		echo "Hi"
	fi
	echo "Best School"
	(( i++ ))
done
